---
docker_apt_url: https://download.docker.com/linux/debian
docker_apt_key_url: https://download.docker.com/linux/debian/gpg

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

# The docker group is root-equivalent.
docker_users: "{{ human_users | map(attribute='name') | list }}"
